name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    workflow_dispatch:

jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "23"

            - name: Install corepack
              run: npm install -g corepack
            
            - name: Enable corepack
              run: corepack enable

            - name: Install dependencies
              run: yarn install

