name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
    workflow_dispatch:

jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "23"
                  cache: "npm"
                  cache-dependency-path: "./yarn.lock"

            - name: Install corepack
              run: npm install -g corepack
            
            - name: Enable corepack
              run: corepack enable

            - name: Install dependencies
              run: yarn install

            # - name: Run tests
              # run: yarn test

            - name: Run build
              run: yarn build
            
            - name: Write SSH keys
              run: |
                  install -m 600 -D /dev/null ~/.ssh/id_rsa
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

            - name: Deploy to server
              run: rsync -a --delete -e "ssh -i ~/.ssh/id_rsa" ${{ github.workspace }}/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}
